// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newspaper.WebApi.Data;

namespace Newspaper.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201231085658_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Newspaper.WebApi.Models.Haber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .HasColumnType("TEXT")
                        .HasMaxLength(28);

                    b.HasKey("Id");

                    b.ToTable("Haberler");
                });

            modelBuilder.Entity("Newspaper.WebApi.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fiyat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yayinevi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .HasColumnType("TEXT");

                    b.Property<string>("isim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
